name: Terraform Module CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.6"  # Match versions.tf

    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Run pre-commit checks
      run: pre-commit run --all-files

  test:
    name: Test
    needs: validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.6"  # Match versions.tf

    - name: Terraform Init
      run: terraform init

    - name: Run Terraform Tests
      # Using -var for project_id in CI, but tests will work with default mock values
      run: terraform test -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
