name: Terraform Module CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.6"  # Match versions.tf

    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Run pre-commit checks
      run: pre-commit run --all-files

  test:
    name: Test
    needs: validate
    runs-on: ubuntu-latest
    env:
      TF_CLI_CONFIG_FILE: ""
      TF_SKIP_PROVIDER_VERIFY: "1"
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.6"  # Match versions.tf

    - name: Terraform Init
      run: terraform init

    - name: Run Terraform Tests
      env:
        TF_VAR_project_id: "test-project"
      run: TF_ACC=1 terraform test
