name: Terraform Module CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.6"  # Match versions.tf

    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Run pre-commit checks
      run: pre-commit run --all-files

  test:
    name: Test
    needs: validate
    runs-on: ubuntu-latest
    env:
      TF_CLI_CONFIG_FILE: ""
      TF_SKIP_PROVIDER_VERIFY: "1"
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.6"  # Match versions.tf

    - name: Terraform Init
      run: terraform init

    - name: Run Terraform Tests
      env:
        GOOGLE_CREDENTIALS: '{"type":"service_account","project_id":"mock-project","private_key_id":"mock-key-id","private_key":"-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n","client_email":"mock-email@mock-project.iam.gserviceaccount.com","client_id":"mock-client-id","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/mock-email%40mock-project.iam.gserviceaccount.com"}'
      run: terraform test
